import argparse
import pathlib
import shlex
import subprocess
import sys


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]


def build_base_cmd() -> list[str]:
    return [
        sys.executable,
        "-m",
        "scripts.change_td3",
        "--seed",
        "42",
        "--total_steps",
        "500000",
        "--gui",
        "false",
        "--eval_gui",
        "false",
        "--eval_stepsleep",
        "false",
        "--action_scale",
        "1.0",
    ]


def build_mode_cmd(mode: str) -> list[str]:
    cmd = build_base_cmd()

    if mode == "baseline":
        cmd += [
            "--use_latent",
            "true",
            "--use_v1trust",
            "false",
            "--actor_updates_encoder",
            "false",
            "--critic_updates_encoder",
            "false",
            "--critic_encoder_grad_scale",
            "0.05",
            "--actor_encoder_grad_scale",
            "0.0",
            "--latent_input_scale",
            "0.1",
            "--log_dir",
            "runs/baseline",
            "--ckpt_dir",
            "checkpoints/baseline",
        ]
    elif mode == "latent_detach":
        cmd += [
            "--use_latent",
            "true",
            "--use_v1trust",
            "false",
            "--latent_only",
            "false",
            "--actor_updates_encoder",
            "false",
            "--critic_updates_encoder",
            "false",
            "--critic_encoder_grad_scale",
            "0.0",
            "--actor_encoder_grad_scale",
            "0.0",
            "--latent_input_scale",
            "0.1",
            "--log_dir",
            "runs/latent_detach",
            "--ckpt_dir",
            "checkpoints/latent_detach",
        ]
    elif mode == "v1trust":
        cmd += [
            "--use_latent",
            "true",
            "--use_v1trust",
            "true",
            "--actor_updates_encoder",
            "false",
            "--critic_updates_encoder",
            "false",
            "--critic_encoder_grad_scale",
            "0.05",
            "--actor_encoder_grad_scale",
            "0.0",
            "--latent_input_scale",
            "0.1",
            "--trust_alpha",
            "0.5",
            "--trust_beta",
            "0.5",
            "--trust_q_min",
            "0.5",
            "--trust_q_max",
            "1.0",
            "--trust_ema_momentum",
            "0.99",
            "--trust_warmup_steps",
            "10000",
            "--log_dir",
            "runs/v1trust",
            "--ckpt_dir",
            "checkpoints/v1trust",
        ]
    elif mode == "v1trust_detach_trust1":
        cmd += [
            "--use_latent",
            "true",
            "--use_v1trust",
            "true",
            "--actor_updates_encoder",
            "false",
            "--critic_updates_encoder",
            "false",
            "--critic_encoder_grad_scale",
            "0.0",
            "--actor_encoder_grad_scale",
            "0.0",
            "--latent_input_scale",
            "0.1",
            "--trust_alpha",
            "0.5",
            "--trust_beta",
            "0.5",
            "--trust_q_min",
            "1.0",
            "--trust_q_max",
            "1.0",
            "--trust_ema_momentum",
            "0.99",
            "--trust_warmup_steps",
            "0",
            "--log_dir",
            "runs/v1trust_detach_trust1",
            "--ckpt_dir",
            "checkpoints/v1trust_detach_trust1",
        ]
    elif mode == "latent_only":
        cmd += [
            "--use_latent",
            "true",
            "--use_v1trust",
            "false",
            "--latent_only",
            "true",
            "--latent_only_variant",
            "base",
            "--actor_updates_encoder",
            "false",
            "--critic_updates_encoder",
            "false",
            "--critic_encoder_grad_scale",
            "0.05",
            "--critic_encoder_grad_schedule",
            "0:0.0,50000:0.03,150000:0.05",
            "--actor_encoder_grad_scale",
            "0.0",
            "--latent_input_scale",
            "1.0",
            "--progress_loss_weight",
            "0.0",
            "--log_dir",
            "runs/latent_only_route_tree_base",
            "--ckpt_dir",
            "checkpoints/latent_only_route_tree_base",
        ]
    elif mode == "latent_only_affordance":
        cmd += [
            "--use_latent",
            "true",
            "--use_v1trust",
            "false",
            "--latent_only",
            "true",
            "--latent_only_variant",
            "affordance",
            "--actor_updates_encoder",
            "false",
            "--critic_updates_encoder",
            "false",
            "--critic_encoder_grad_scale",
            "0.05",
            "--critic_encoder_grad_schedule",
            "0:0.0,50000:0.03,150000:0.05",
            "--actor_encoder_grad_scale",
            "0.0",
            "--latent_input_scale",
            "1.0",
            "--progress_loss_weight",
            "0.0",
            "--affordance_loss_weight",
            "0.005",
            "--affordance_start_step",
            "100000",
            "--affordance_gamma",
            "0.95",
            "--affordance_bootstrap_warmup_steps",
            "50000",
            "--affordance_danger_range",
            "0.20",
            "--affordance_goal_tolerance",
            "0.20",
            "--log_dir",
            "runs/latent_only_affordance_dim16",
            "--ckpt_dir",
            "checkpoints/latent_only_affordance_dim16",
        ]
    elif mode == "hierarchical_async":
        cmd += [
            "--use_latent",
            "true",
            "--hierarchical_async",
            "true",
            "--latent_only",
            "false",
            "--use_v1trust",
            "false",
            "--latent_dim",
            "16",
            "--latent_input_scale",
            "1.0",
            "--reference_sequence_length",
            "15",
            "--high_level_interval",
            "8",
            "--reference_valid_steps",
            "120",
            "--reference_loss_weight",
            "0.05",
            "--reference_smoothness_weight",
            "0.01",
            "--high_level_actor_grad_scale",
            "0.0",
            "--hierarchical_action_l2_weight",
            "0.10",
            "--hierarchical_motor_balance_weight",
            "0.10",
            "--hierarchical_action_delta_weight",
            "0.10",
            "--hierarchical_normalize_actor_q",
            "true",
            "--motor_collective_fraction",
            "0.60",
            "--motor_differential_fraction",
            "0.25",
            "--curriculum_success_gated",
            "true",
            "--eval_episodes",
            "3",
            "--reference_lookahead_points",
            "3",
            "--action_scale",
            "0.75",
            "--log_dir",
            "runs/hierarchical_async_v2",
            "--ckpt_dir",
            "checkpoints/hierarchical_async_v2",
        ]
    elif mode == "reference_tracking":
        cmd += [
            "--use_latent",
            "false",
            "--reference_tracking",
            "true",
            "--hierarchical_async",
            "false",
            "--latent_only",
            "false",
            "--use_v1trust",
            "false",
            "--num_trees",
            "0",
            "--route_blocking_tree",
            "false",
            "--curriculum",
            "false",
            "--rule_reference_mode",
            "line",
            "--reference_sequence_length",
            "15",
            "--reference_horizon_seconds",
            "1.0",
            "--high_level_interval",
            "8",
            "--reference_lookahead_points",
            "3",
            "--max_reference_speed",
            "0.6",
            "--max_reference_acceleration",
            "1.5",
            "--max_reference_vertical_speed",
            "0.4",
            "--teacher_timesteps",
            "5000",
            "--teacher_supervision_timesteps",
            "15000",
            "--tracking_actor_rl_start_step",
            "15000",
            "--teacher_exploration_noise",
            "0.03",
            "--teacher_bc_updates_per_step",
            "2",
            "--motor_action_mode",
            "asymmetric_rpm",
            "--start_timesteps",
            "5000",
            "--update_after",
            "1000",
            "--expl_noise_start",
            "0.15",
            "--expl_noise_end",
            "0.05",
            "--noise_decay_steps",
            "50000",
            "--reward_scale",
            "0.1",
            "--action_scale",
            "1.0",
            "--eval_episodes",
            "5",
            "--log_dir",
            "runs/reference_tracking_v1",
            "--ckpt_dir",
            "checkpoints/reference_tracking_v1",
        ]
    elif mode == "upper_dslpid":
        cmd += [
            "--use_latent",
            "false",
            "--learned_upper_dslpid",
            "true",
            "--hierarchical_async",
            "false",
            "--reference_tracking",
            "false",
            "--latent_only",
            "false",
            "--use_v1trust",
            "false",
            "--num_trees",
            "24",
            "--route_blocking_tree",
            "false",
            "--curriculum",
            "false",
            "--curriculum_stage_override",
            "0",
            "--reference_sequence_length",
            "15",
            "--reference_horizon_seconds",
            "1.0",
            "--high_level_interval",
            "8",
            "--max_reference_speed",
            "0.8",
            "--max_reference_acceleration",
            "1.0",
            "--max_reference_vertical_speed",
            "0.3",
            "--max_reference_vertical_acceleration",
            "0.5",
            "--start_timesteps",
            "2000",
            "--update_after",
            "1000",
            "--expl_noise_start",
            "0.20",
            "--expl_noise_end",
            "0.05",
            "--noise_decay_steps",
            "50000",
            "--reward_scale",
            "0.1",
            "--eval_episodes",
            "5",
            "--action_scale",
            "1.0",
            "--log_dir",
            "runs/upper_dslpid_velocity_v2",
            "--ckpt_dir",
            "checkpoints/upper_dslpid_velocity_v2",
        ]
    elif mode == "upper_dslpid_one_tree":
        cmd += [
            "--use_latent",
            "false",
            "--learned_upper_dslpid",
            "true",
            "--hierarchical_async",
            "false",
            "--reference_tracking",
            "false",
            "--latent_only",
            "false",
            "--use_v1trust",
            "false",
            "--num_trees",
            "24",
            "--route_blocking_tree",
            "true",
            "--route_tree_fraction",
            "0.5",
            "--curriculum",
            "false",
            "--curriculum_stage_override",
            "0",
            "--reference_sequence_length",
            "15",
            "--reference_horizon_seconds",
            "1.0",
            "--high_level_interval",
            "8",
            "--max_reference_speed",
            "0.8",
            "--max_reference_acceleration",
            "1.0",
            "--max_reference_vertical_speed",
            "0.3",
            "--max_reference_vertical_acceleration",
            "0.5",
            "--start_timesteps",
            "0",
            "--update_after",
            "1000",
            "--expl_noise_start",
            "0.20",
            "--expl_noise_end",
            "0.05",
            "--noise_decay_steps",
            "50000",
            "--reward_scale",
            "0.1",
            "--eval_episodes",
            "5",
            "--action_scale",
            "1.0",
            "--load_checkpoint",
            "checkpoints/upper_dslpid_velocity_v2/baseline_clear_route/model_best",
            "--log_dir",
            "runs/upper_dslpid_one_tree_v1",
            "--ckpt_dir",
            "checkpoints/upper_dslpid_one_tree_v1",
        ]
    elif mode == "upper_dslpid_five_trees":
        cmd += [
            "--use_latent", "false",
            "--learned_upper_dslpid", "true",
            "--hierarchical_async", "false",
            "--reference_tracking", "false",
            "--latent_only", "false",
            "--use_v1trust", "false",
            "--num_trees", "0",
            "--route_blocking_tree", "true",
            "--route_blocking_tree_count", "5",
            "--route_tree_lateral_range", "0.55",
            "--route_tree_layout", "fixed_safe_five",
            "--curriculum", "false",
            "--curriculum_stage_override", "0",
            "--reference_sequence_length", "15",
            "--reference_horizon_seconds", "1.0",
            "--high_level_interval", "8",
            "--max_reference_speed", "0.8",
            "--max_reference_acceleration", "1.0",
            "--max_reference_vertical_speed", "0.3",
            "--max_reference_vertical_acceleration", "0.5",
            "--start_timesteps", "0",
            "--update_after", "1000",
            "--expl_noise_start", "0.20",
            "--expl_noise_end", "0.05",
            "--noise_decay_steps", "50000",
            "--reward_scale", "0.1",
            "--distance_reward_weight", "0.0",
            "--time_penalty_weight", "0.01",
            "--eval_episodes", "10",
            "--action_scale", "1.0",
            "--load_checkpoint", "checkpoints/upper_dslpid_one_tree_v1/model_final",
            "--log_dir", "runs/upper_dslpid_five_trees_fixed_v2",
            "--ckpt_dir", "checkpoints/upper_dslpid_five_trees_fixed_v2",
        ]
    elif mode == "upper_dslpid_five_trees_forest24":
        cmd += [
            "--use_latent", "false",
            "--learned_upper_dslpid", "true",
            "--hierarchical_async", "false",
            "--reference_tracking", "false",
            "--latent_only", "false",
            "--use_v1trust", "false",
            "--num_trees", "24",
            "--route_blocking_tree", "true",
            "--route_blocking_tree_count", "5",
            "--route_tree_layout", "fixed_safe_five",
            "--curriculum", "false",
            "--curriculum_stage_override", "0",
            "--reference_sequence_length", "15",
            "--reference_horizon_seconds", "1.0",
            "--high_level_interval", "8",
            "--max_reference_speed", "0.8",
            "--max_reference_acceleration", "1.0",
            "--max_reference_vertical_speed", "0.3",
            "--max_reference_vertical_acceleration", "0.5",
            "--start_timesteps", "0",
            "--update_after", "1000",
            "--expl_noise_start", "0.15",
            "--expl_noise_end", "0.05",
            "--noise_decay_steps", "50000",
            "--reward_scale", "0.1",
            "--distance_reward_weight", "0.0",
            "--time_penalty_weight", "0.01",
            "--eval_episodes", "10",
            "--action_scale", "1.0",
            "--load_checkpoint", "checkpoints/upper_dslpid_five_trees_fixed_v2/model_best",
            "--log_dir", "runs/upper_dslpid_five_trees_forest24_v1",
            "--ckpt_dir", "checkpoints/upper_dslpid_five_trees_forest24_v1",
        ]
    elif mode == "upper_dslpid_semantic_latent":
        cmd += [
            "--use_latent", "false",
            "--learned_upper_dslpid", "true",
            "--upper_semantic_latent", "true",
            "--semantic_history_length", "4",
            "--latent_dim", "16",
            "--semantic_residual_scale", "0.25",
            "--semantic_loss_weight", "0.2",
            "--semantic_danger_range", "0.20",
            "--base_policy_checkpoint",
            "checkpoints/upper_dslpid_five_trees_forest24_v1/baseline_pre_semantic_latent/model_best",
            "--hierarchical_async", "false",
            "--reference_tracking", "false",
            "--latent_only", "false",
            "--use_v1trust", "false",
            "--num_trees", "24",
            "--route_blocking_tree", "true",
            "--route_blocking_tree_count", "5",
            "--route_tree_layout", "fixed_safe_five",
            "--curriculum", "false",
            "--curriculum_stage_override", "0",
            "--reference_sequence_length", "15",
            "--reference_horizon_seconds", "1.0",
            "--high_level_interval", "8",
            "--max_reference_speed", "0.8",
            "--max_reference_acceleration", "1.0",
            "--max_reference_vertical_speed", "0.3",
            "--max_reference_vertical_acceleration", "0.5",
            "--start_timesteps", "0",
            "--update_after", "1000",
            "--expl_noise_start", "0.10",
            "--expl_noise_end", "0.03",
            "--noise_decay_steps", "50000",
            "--reward_scale", "0.1",
            "--distance_reward_weight", "0.0",
            "--time_penalty_weight", "0.01",
            "--eval_episodes", "10",
            "--action_scale", "1.0",
            "--log_dir", "runs/upper_dslpid_semantic_latent_v1",
            "--ckpt_dir", "checkpoints/upper_dslpid_semantic_latent_v1",
        ]
    elif mode in ("nolatent", "nolantent"):
        cmd += [
            "--use_latent",
            "false",
            "--use_v1trust",
            "false",
            "--log_dir",
            "runs/nolatent",
            "--ckpt_dir",
            "checkpoints/nolatent",
        ]
    else:
        raise ValueError(f"Unsupported mode: {mode}")

    return cmd


def main():
    parser = argparse.ArgumentParser(description="Quick launcher for change_td3 experiment modes.")
    parser.add_argument(
        "mode",
        choices=[
            "baseline",
            "latent_detach",
            "v1trust",
            "v1trust_detach_trust1",
            "latent_only",
            "latent_only_affordance",
            "hierarchical_async",
            "reference_tracking",
            "upper_dslpid",
            "upper_dslpid_one_tree",
            "upper_dslpid_five_trees",
            "upper_dslpid_five_trees_forest24",
            "upper_dslpid_semantic_latent",
            "nolatent",
            "nolantent",
        ],
        help="Experiment preset to launch.",
    )
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--total_steps", type=int, default=None)
    parser.add_argument("--gui", choices=["true", "false"], default=None)
    parser.add_argument("--eval_gui", choices=["true", "false"], default=None)
    args, extra = parser.parse_known_args()

    cmd = build_mode_cmd(args.mode)

    if args.seed is not None:
        cmd[cmd.index("--seed") + 1] = str(args.seed)
    if args.total_steps is not None:
        cmd[cmd.index("--total_steps") + 1] = str(args.total_steps)
    if args.gui is not None:
        cmd[cmd.index("--gui") + 1] = args.gui
    if args.eval_gui is not None:
        cmd[cmd.index("--eval_gui") + 1] = args.eval_gui

    if extra:
        if extra and extra[0] == "--extra":
            extra = extra[1:]
        if extra and extra[0] == "--":
            extra = extra[1:]
        cmd.extend(extra)

    print("Launching:")
    print(" ".join(shlex.quote(part) for part in cmd))
    subprocess.run(cmd, cwd=REPO_ROOT, check=True)


if __name__ == "__main__":
    main()
